development:
 adapter: postgresql
 encoding: utf8
 host: localhost
 port: 5432
 database: myapp_development
 pool: 5
 username: postgres
 password: 123


test:
 adapter: postgresql
 encoding: utf8
 host: localhost
 port: 5432
 database: myapp_test
 pool: 5
 username: postgres
 password: 123


production:
 adapter: postgresql
 encoding: utf8
 host: localhost
 port: 5432
 database: myapp_production
 pool: 5
 username: postgres
 password: 123
